AWSTemplateFormatVersion: 2010-09-09
Description: VPC template for Advanced Networks


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network Configuration
      Parameters:
      - VPCCIDR
      - PublicSubnet1CIDR
      - PrivateSubnet1CIDR
      - PeerVPCCIDR
      - PeerPublicSubnet1CIDR
      - PeerPrivateSubnet1CIDR
    - Label:
        default: Instance Configuration
      Parameters:
      - BastionKeyPairName
    ParameterLabels:
      VPCCIDR:
        default: VPC CIDR
      PublicSubnet1CIDR:
        default: Public subnet 1 CIDR
      PrivateSubnet1CIDR:
        default: Private subnet 1 CIDR
      PeerVPCCIDR:
        default: Peer VPC CIDR
      PeerPublicSubnet1CIDR:
        default: Peer Public subnet 1 CIDR
      PeerPrivateSubnet1CIDR:
        default: Peer Private subnet 1 CIDR
      SSHRemoteAccessCIDR:
        default: Allowed bastion external access CIDR
      BastionKeyPairName:
        default: Bastion host key pair name


Parameters:
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 11.0.0.0/16
    Description: CIDR Block for the VPC
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 11.0.1.0/24
    Description: CIDR Block for the public DMZ subnet 1 located in Availability Zone 1
    Type: String
  PrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 11.0.10.0/24
    Description: CIDR block for private subnet 1 located in Availability Zone 1
    Type: String
  PeerVPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 12.0.0.0/16
    Description: CIDR Block for the VPC
    Type: String
  PeerPublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 12.0.1.0/24
    Description: CIDR Block for the public DMZ subnet 1 located in Availability Zone 1
    Type: String
  PeerPrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Default: 12.0.10.0/24
    Description: CIDR block for private subnet 1 located in Availability Zone 1
    Type: String
  SSHRemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for external SSH access to the bastions
    Type: String
    Default: 194.126.117.170/32
  BastionKeyPairName: 
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"
    ConstraintDescription: must be a valid Key Pair
    Default: "WP"


Resources:
  AnVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-automated-objects.s3.eu-central-1.amazonaws.com/vpc.yaml
      Parameters:
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        VPCCIDR: !Ref VPCCIDR

  PeerAnVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-automated-objects.s3.eu-central-1.amazonaws.com/peer-vpc.yaml
      Parameters:
        PrivateSubnet1CIDR: !Ref PeerPrivateSubnet1CIDR
        PublicSubnet1CIDR: !Ref PeerPublicSubnet1CIDR
        VPCCIDR: !Ref PeerVPCCIDR

  #AnBastionStack:
  #  Type: AWS::CloudFormation::Stack
  #  Properties:
  #    TemplateURL: https://cfn-automated-objects.s3.eu-central-1.amazonaws.com/ec2.yaml
  #    Parameters:
  #      VPCID: !GetAtt AnVPCStack.Outputs.AnVPCID
  #      VPCSubnetID: !GetAtt AnVPCStack.Outputs.AnPublicSubnet1
  #      SSHRemoteAccessCIDR: !Ref SSHRemoteAccessCIDR
  #      BastionKeyPairName: !Ref BastionKeyPairName